http://localhost:4000/
###
http://localhost:4000/blocks
###
http://localhost:4000/blocks/acc8ac06070d443b271bf264e05e355a1559532e6f5625cbbedc95909717cda7
###
POST http://localhost:4000/blocks

{
    "message":"Data For My block"
}
###
http://localhost:4000/balance/igson?total=true

###
http://localhost:4000/balance/Lynn?total=true

###
http://localhost:4000/balance/igson

###
http://localhost:4000/balance/Lynn

### 
POST http://localhost:4000/transaction

{
    "to":"Lynn",
    "amount":100
}

###
http://localhost:4000/mempool